theme: jekyll-theme-minimal
logo: img/JustNotSorry-logo.png
title: Just Not Sorry
google_analytics: UA-3535278-4
description: The Chrome Extension for Gmail and Outlook.com that helps you send more confident emails by warning you when you use words which undermine your message.