theme: jekyll-theme-minimal
logo: img/JustNotSorry-logo.png
title: Just Not Sorry
description: The Chrome Extension that helps you send more confident emails by warning you when you use words which undermine your message.