name: Publish justnotsorry.com

on:
  push:
    branches:
      - main
    paths:
      - 'site/**'
      - 'package.json'
      - 'src/warnings/phrases.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build and deploy justnotsorry.com
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git config user.email "just-not-sorry@defmethod.com"
          git config user.name "just-not-sorry-bot"
          npm run deploy
